# Basic
title: ê¹€í˜œì§„
subtitle: ê°œì¸ ë¸”ë¡œê·¸
description: 21ì‚´, ì„±ì¥ ì¤‘ì¸ ê°œë°œìì˜ ë¸”ë¡œê·¸ì…ë‹ˆë‹¤.
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: Chloe
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: Web FrontEnd Developer
url: "https://hyejin-1010.github.io"

# Comment
comment:
    disqus: Hyejin
    # gitment: xxx // éœ€è¦ä¿®æ”¹ comments.htmlä¸­çš„client_idå’Œclient_secret
    # uyan: 2143225  # æœ‰è¨€id,ç™»å½•æœ‰è¨€å®˜ç½‘ç”³è¯·

# Social
social:
    github: hyejin-1010
    # twitter: 
    mail: hyepago@gmail.com


# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
baidu:
    id: xxxx  

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
ga:
    id: xxxx  
    host: auto  


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/hyejin-1010/hyejin-1010.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: Home

# Navigation buttons in the front page.s
nav:
    - {title: Archive, description: archive, url: '/archive'}   
    - {title: Tag, description: tags, url: '/tags'}      
    - {title: About, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


